version: 0.2

env:
  variables:
    PEM_BUCKET: test-key-file-upload
    PEM_KEY: deploy-javaApp.pem
    S3_BUCKET: test-war-file-upload
    S3_KEY: build-artifacts/Ecomm.war
    EC2_USER: ec2-user
    EC2_HOST: ec2-54-236-5-156.compute-1.amazonaws.com

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "🔧 Installing CodeBuild dependencies..."
      - yum install -y unzip awscli openssh

  pre_build:
    commands:
      - echo "🔐 Downloading PEM key from S3..."
      - aws s3 cp s3://$PEM_BUCKET/$PEM_KEY ec2-key.pem
      - chmod 400 ec2-key.pem

  build:
    commands:
      - echo "📦 Downloading WAR from S3..."
      - aws s3 cp s3://$S3_BUCKET/$S3_KEY Ecomm.war

      - echo "🚚 Copying WAR to EC2..."
      - scp -o StrictHostKeyChecking=no -i ec2-key.pem Ecomm.war $EC2_USER@$EC2_HOST:/home/ec2-user/

      - echo "🛠️ Installing Tomcat and deploying WAR on EC2..."
      - >
        ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST <<'EOF'
        set -e
        echo "🔧 Installing Java and wget"
        sudo yum install -y java-11-openjdk wget

        echo "📁 Creating Tomcat directory"
        sudo mkdir -p /opt/tomcat
        cd /opt/tomcat

        echo "⬇️ Downloading Tomcat..."
        sudo wget https://downloads.apache.org/tomcat/tomcat-10/v10.1.42/bin/apache-tomcat-10.1.42.tar.gz

        echo "📦 Extracting Tomcat..."
        sudo tar -xvzf apache-tomcat-10.1.42.tar.gz
        sudo mv apache-tomcat-10.1.42 tomcat
        sudo rm apache-tomcat-10.1.42.tar.gz

        echo "🚀 Deploying WAR file"
        sudo mv /home/ec2-user/Ecomm.war /opt/tomcat/tomcat/webapps/

        echo "🎛️ Starting Tomcat"
        sudo chmod +x /opt/tomcat/tomcat/bin/*.sh
        sudo /opt/tomcat/tomcat/bin/shutdown.sh || true
        sudo /opt/tomcat/tomcat/bin/startup.sh

        echo "📡 Checking if Tomcat is listening on port 8080..."
        sudo netstat -tuln | grep 8080 || echo "❌ Port 8080 is not open"
EOF

  post_build:
    commands:
      - echo "✅ Tomcat deployment completed successfully."

artifacts:
  files:
    - Ecomm.war
