version: 0.2

env:
  variables:
    S3_BUCKET: "test-war-file"                             # Replace with your WAR bucket
    S3_KEY: "build-artifacts/Ecomm1.war"                   # Your WAR path
    EC2_USER: "ec2-user"
    EC2_HOST: "ec2-xx-xx-xx-xx.compute.amazonaws.com"      # Replace with your EC2 public IP or DNS
    PEM_BUCKET: "bucket-for-pem-file"                      # S3 bucket that stores .pem file
    PEM_KEY: "tomcat-server.pem"                           # PEM file name

phases:
  install:
    commands:
      - echo Installing tools...
      - yum install -y unzip awscli openssh
  pre_build:
    commands:
      - echo Downloading PEM key from S3...
      - aws s3 cp s3://$PEM_BUCKET/$PEM_KEY ec2-key.pem
      - chmod 400 ec2-key.pem
  build:
    commands:
      - echo Downloading WAR from S3...
      - aws s3 cp s3://$S3_BUCKET/$S3_KEY Ecomm1.war

      - echo Copying WAR to EC2...
      - scp -o StrictHostKeyChecking=no -i ec2-key.pem Ecomm1.war $EC2_USER@$EC2_HOST:/home/ec2-user/

      - echo Deploying WAR to Tomcat...
      - ssh -o StrictHostKeyChecking=no -i ec2-key.pem $EC2_USER@$EC2_HOST <<EOF
          sudo mv /home/ec2-user/Ecomm1.war /opt/apache-tomcat-10.1.42/webapps/
          sudo /opt/apache-tomcat-10.1.42/bin/shutdown.sh || true
          sudo /opt/apache-tomcat-10.1.42/bin/startup.sh
        EOF

  post_build:
    commands:
      - echo ✅ Deployment to EC2 Tomcat completed.

artifacts:
  files:
    - Ecomm1.war
